# Generated by Django 4.2.16 on 2024-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="active",
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENABLED", "Active"),
                    ("DISABLED", "Disabled"),
                    ("HIDDEN", "Hidden"),
                ],
                default="ENABLED",
                max_length=50,
                verbose_name="Usage status",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="status",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("FREEZE", "Frozen")],
                default="VALID",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
