# Generated by Django 4.2.5 on 2024-02-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={
                "verbose_name": "Nomenclature source",
                "verbose_name_plural": "Nomenclature sources",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={
                "verbose_name": "Type of nomenclature",
                "verbose_name_plural": "Type of nomenclatures",
            },
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_nomenclature",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Parent nomenclature",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Is used"),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="mnemonic",
            field=models.CharField(max_length=50, verbose_name="Mnemonic"),
        ),
        migrations.AlterField(
            model_name="source",
            name="create_date",
            field=models.DateField(verbose_name="Official creation date"),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="source",
            name="update_date",
            field=models.DateField(verbose_name="Official modification date"),
        ),
        migrations.AlterField(
            model_name="type",
            name="create_date",
            field=models.DateField(verbose_name="Official creation date"),
        ),
        migrations.AlterField(
            model_name="type",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="type",
            name="mnemonic",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Mnemonic"
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="status",
            field=models.CharField(
                choices=[("VALID", "Valid"), ("FREEZE", "Frozen")],
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="update_date",
            field=models.DateField(verbose_name="Official modification date"),
        ),
    ]
