# Generated by Django 4.2.10 on 2024-03-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sinp_nomenclatures",
            "0004_alter_source_options_alter_type_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="nomenclature",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="source",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="source",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="type",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="type",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nomenclatures",
                to="sinp_nomenclatures.type",
                verbose_name="Type",
            ),
        ),
    ]
