# Generated by Django 4.2.11 on 2024-04-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0005_remove_nomenclature_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={
                "verbose_name": "source",
                "verbose_name_plural": "sources",
            },
        ),
        migrations.AddField(
            model_name="source",
            name="url",
            field=models.URLField(
                blank=True,
                max_length=250,
                verbose_name="URL",  # noqa: DJ01
            ),
        ),
    ]
