# Generated by Django 4.2.11 on 2024-04-03 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0006_alter_source_options_source_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomenclature",
            name="mnemonic",
        ),
    ]
