# Generated by Django 4.2.11 on 2024-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sinp_nomenclatures", "0007_remove_nomenclature_mnemonic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Description"
            ),
            preserve_default=False,
        ),
    ]
