name: "📚 Documentation"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/*/**"
      - "plugin_qgis_lpo/**/*.py"
      - "plugin_qgis_lpo/metadata.txt"
      - "requirements/documentation.txt"
    tags:
      - "*"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/documentation.yml"
      - docs/**/*
      - requirements/documentation.txt

  workflow_dispatch:

# Allow one concurrent deployment per branch/pr
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: "requirements/documentation.txt"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run image
        uses: abatilo/actions-poetry@v3
        #------------------------------------
        #  -----  Install dependencies  -----
        #------------------------------------
      - name: Install dependencies
        run: poetry install --only=docs

      - name: Build doc using Sphinx
        run: poetry run sphinx-build -b html -d docs/_build/cache -j auto docs docs/_build/html

      - name: Save build doc as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html/*
          if-no-files-found: error
          retention-days: 30

      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
        with:
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
        uses: actions/deploy-pages@v4
